import * as abilities from "./abilities";
import { burrower, character, core, endlessMultitude, feederTendrils, fly, hiveTentril, hiveTyrantKeyword, hornedChitin, infantry, monster, psycher1Keyword, psycher2Keyword, sporeCaster, swarm, synapse, toxicLashes, tyranids, psycher2_2Keyword, carnifexKeyword, acidBlood, aircraft } from "./Keywords";
import { smite } from "./psychicPowers";
import { acidMawWargear, adrenalGlands, biostaticRattle, chitinThrons, enhancedSenses, extendedCarapace, fleshHooks, infestationNode, lashWhip, prehensilePincerTail, sporeCysts, toxinSacs, toxinSpike, tusks } from "./Wargear";
import * as weapons from "./weapons";


export const units = [
    {
        name: 'Hive Tyrant',
        type: 'monster',
        role: 'hq',
        stats: [{
            m: '9"',
            ws: '2+',
            bs: '2+',
            s: '7',
            t: '8',
            w: '12',
            a: '5',
            ld: '10',
            sv: '2+',
        },{
            m: '8"',
            ws: '3+',
            bs: '3+',
            s: '7',
            t: '8',
            w: '<7',
            a: '5',
            ld: '10',
            sv: '2+',
        },{
            m: '6"',
            ws: '4+',
            bs: '4+',
            s: '7',
            t: '8',
            w: '<4',
            a: '5',
            ld: '10',
            sv: '2+',
        }],
        keywords: [
            monster,
            character,
            synapse,
            psycher2Keyword,
            hornedChitin,
            hiveTyrantKeyword,
            hiveTentril,
            tyranids,
        ],
        weapons: [
            weapons.tyrantVenomCannon,
            weapons.tyrantStranglethron,
            weapons.tyrantBonesword,
            weapons.tyrantScythingTalons
        ],
        abilities: [
            abilities.psychicBarrier,
            abilities.willOfTheHiveMind,
            abilities.deathThroes,
            abilities.shadowInTheWarp,
            abilities.relentlessFurocity,
        ],
        wargear: [
            adrenalGlands,
            toxinSacs,
            {...lashWhip, active: true},
        ],
    },
    {
        name: 'Winged Hive Tyrant',
        type: 'monster',
        role: 'hq',
        stats: [{
            m: '16"',
            ws: '2+',
            bs: '2+',
            s: '7',
            t: '7',
            w: '12',
            a: '5',
            ld: '10',
            sv: '2+',
        },{
            m: '12"',
            ws: '3+',
            bs: '3+',
            s: '7',
            t: '7',
            w: '<7',
            a: '5',
            ld: '10',
            sv: '2+',
        },{
            m: '8"',
            ws: '4+',
            bs: '4+',
            s: '7',
            t: '7',
            w: '<4',
            a: '5',
            ld: '10',
            sv: '2+',
        }],
        keywords: [
            monster,
            fly,
            character,
            synapse,
            psycher2Keyword,
            hornedChitin,
            hiveTyrantKeyword,
            hiveTentril,
            tyranids,
        ],
        weapons: [
            weapons.tyrantVenomCannon,
            weapons.tyrantStranglethron,
            weapons.tyrantBonesword,
            weapons.tyrantScythingTalons,
            weapons.tyrantTalons,
        ],
        abilities: [
            abilities.psychicBarrier,
            abilities.willOfTheHiveMind,
            abilities.deathFromAbove,
            abilities.deathThroes,
            abilities.shadowInTheWarp,
            abilities.relentlessFurocity,
        ],
        wargear: [
            adrenalGlands,
            toxinSacs,
            {...lashWhip, active: true},
            {...prehensilePincerTail, active: true}
        ],
    },
    {
        name: 'Tervigon',
        type: 'monster',
        role: 'hq',
        stats: [{
            m: '8"',
            ws: '3+',
            bs: '3+',
            s: '7',
            t: '8',
            w: '17',
            a: '4',
            ld: '10',
            sv: '2+',
        },{
            m: '7"',
            ws: '4+',
            bs: '4+',
            s: '7',
            t: '8',
            w: '<9',
            a: '4',
            ld: '10',
            sv: '2+',
        },{
            m: '6"',
            ws: '5+',
            bs: '5+',
            s: '7',
            t: '8',
            w: '<5',
            a: '5',
            ld: '10',
            sv: '2+',
        }],
        keywords: [
            monster,
            character,
            synapse,
            psycher1Keyword,
            hiveTentril,
            tyranids,
        ],
        weapons: [
            weapons.stingerSalvoes,
            weapons.tervigonCrushingClaws,
            weapons.tervigonTalonsStrike,
            weapons.tervigonTalonsSweep,
        ],
        abilities: [
            abilities.spawnTermagants,
            abilities.broodProgenitor,
            abilities.wallOfflesh,
            abilities.deathThroes,
            abilities.shadowInTheWarp,
            abilities.surgingVitality,
        ],
        wargear: [
            adrenalGlands,
            toxinSacs,
        ],
    },
    {
        name: 'Neurothrope',
        type: 'infantry',
        role: 'hq',
        stats: [{
            m: '6"',
            ws: '5+',
            bs: '3+',
            s: '5',
            t: '5',
            w: '6',
            a: '2',
            ld: '10',
            sv: '5+',
        }],
        keywords: [
            infantry,
            character,
            fly,
            synapse,
            psycher2_2Keyword,
            hornedChitin,
            hiveTentril,
            tyranids,
        ],
        weapons: [
            weapons.defaultMeleeAttack
        ],
        abilities: [
            abilities.warpField3,
            abilities.psychicNode,
            abilities.spiritLeech,
            abilities.warpSiphon,
            abilities.shadowInTheWarp,
            abilities.psychicAugmentation,
        ],
        wargear: [
        ],
    },
    {
        name: 'Trygon Prime',
        type: 'monster',
        role: 'hq',
        stats: [{
            m: '10"',
            ws: '3+',
            bs: '3+',
            s: '7',
            t: '7',
            w: '14',
            a: '12',
            ld: '10',
            sv: '3+',
        },{
            m: '8"',
            ws: '4+',
            bs: '4+',
            s: '7',
            t: '7',
            w: '<7',
            a: '12',
            ld: '10',
            sv: '3+',
        },{
            m: '6"',
            ws: '5+',
            bs: '5+',
            s: '7',
            t: '7',
            w: '<4',
            a: '12',
            ld: '10',
            sv: '3+',
        }],
        keywords: [
            monster,
            burrower,
            synapse,
            character,
            hiveTentril,
            tyranids,
        ],
        weapons: [
            weapons.trygonBioPulseWithContainmentSpines,
            weapons.trygonTalons,
        ],
        abilities:[
            abilities.deathFromBelow,
            abilities.serpentineCoils,
            abilities.bioImpulses,
            abilities.shadowInTheWarp,
            abilities.deathThroes,
            abilities.thrashingDemise,
        ],
        wargear: [
            adrenalGlands,
            toxinSacs,
            prehensilePincerTail,
            biostaticRattle,
            {active: true, ...toxinSpike},
        ],
    },
    {
        name: 'Tyranid Prime',
        type: 'infantry',
        role: 'hq',
        stats: [{
            m: '6"',
            ws: '2+',
            bs: '2+',
            s: '5',
            t: '5',
            w: '6',
            a: '4',
            ld: '10',
            sv: '3+',
        }],
        keywords: [
            synapse,
            infantry,
            character,
            hiveTentril,
            tyranids,
        ],
        weapons:[
            weapons.warriorDeathspitter,
            weapons.warriorDevourer,
            weapons.warriorSpinefists,
            weapons.warriorBarbedStrangler,
            weapons.warriorVenomCannon,
            weapons.warriorBonesword,
            weapons.warriorDualBonesword,
            weapons.warriorRendingClaw,
            weapons.warriorScythingtalon,
        ],
        abilities: [
            abilities.alphaWarrior,
            abilities.guideMind,
            abilities.shadowInTheWarp,
        ],
        wargear: [
            adrenalGlands,
            toxinSacs,
            fleshHooks,
            {...lashWhip, active: true},
        ],
    },
    
    {
        name: 'Broodlord',
        type: 'infantry',
        role: 'hq',
        stats: [{
            m: '8"',
            ws: '2+',
            bs: '6+',
            s: '5',
            t: '5',
            w: '7',
            a: '6',
            ld: '10',
            sv: '4+',
        }],
        keywords: [
            infantry,
            character,
            psycher1Keyword,
            hiveTentril,
            tyranids,
        ],
        weapons: [
            weapons.broodlordClaws
        ],
        abilities: [
            abilities.broodlordLightningReflexes,
            abilities.vanguardPredator,
            abilities.viciousInsight,
            abilities.shadowInTheWarp
        ],
    },
    {
        name: 'Zoanthrope',
        type: 'infantry',
        role: 'elite',
        stats: [{
            m: '6"',
            ws: '5+',
            bs: '3+',
            s: '5',
            t: '5',
            w: '4',
            a: '2',
            ld: '9',
            sv: '5+',
        }],
        keywords: [
            infantry,
            core,
            fly,
            synapse,
            psycher1Keyword,
            hiveTentril,
            tyranids,
        ],
        weapons: [
            weapons.defaultMeleeAttack
        ],
        abilities: [
            abilities.warpField4,
            abilities.warpBlast,
            abilities.shadowInTheWarp,
            abilities.psybroodCoterie,
            abilities.warpShielding,
        ],
        wargear: [
        ],
        psychicPowers: [
            smite,
        ]
    },
    {
        name: 'Genestealers',
        type: 'infantry',
        role: 'elite',
        stats: [{
            m: '8"',
            ws: '3+',
            bs: '6+',
            s: '4',
            t: '4',
            w: '1',
            a: '4',
            ld: '8',
            sv: '5+',
        }],
        keywords: [
            infantry,
            core,
            feederTendrils,
            hiveTentril,
            tyranids,
        ],
        weapons: [
            weapons.genestealerClaws
        ],
        abilities: [
            abilities.lightningReflexes,
            abilities.vanguardPredator,
            abilities.infiltrationSpawning,
            abilities.insidiousInfestation,
            abilities.insidiousinfestationAction,
        ],
        wargear: [
            toxinSacs,
            {...fleshHooks, active: true},
            infestationNode,
            {...acidMawWargear, active: true},
            extendedCarapace,
        ],
    },
    {
        name: 'Venomthrope',
        type: 'infantry',
        role: 'elite',
        stats: [{
            m: '8"',
            ws: '3+',
            bs: '3+',
            s: '5',
            t: '5',
            w: '4',
            a: '5',
            ld: '5',
            sv: '4+',
        }],
        keywords: [
            infantry,
            core,
            fly,
            sporeCaster,
            toxicLashes,
            feederTendrils,
            hiveTentril,
            tyranids,
        ],
        weapons: [
            weapons.venomthropeLashes,
        ],
        abilities: [
            abilities.graspingTendrils,
            abilities.toxicMiasma,
            abilities.foulSpores
        ]
    },
    {
        name: 'Pyrovore',
        type: 'infantry',
        role: 'elite',
        stats: [{
            m: '5"',
            ws: '3+',
            bs: '3+',
            s: '5',
            t: '5',
            w: '5',
            a: '3',
            ld: '5',
            sv: '3+',
        }],
        keywords: [
            infantry,
            core,
            acidBlood,
            hiveTentril,
            tyranids,
        ],
        weapons: [
            weapons.flamespurtBurningSpray,
            weapons.flamespurtPyrogout,
            weapons.bludgeoningFists,           
        ],
        wargear: [
            acidMawWargear,
        ],
        abilities: [
            abilities.volatile,
        ]
    },
    {
        name: 'Termigant',
        type: 'infantry',
        role: 'troops',
        stats: [{
            m: '6"',
            ws: '4+',
            bs: '4+',
            s: '3',
            t: '3',
            w: '1',
            a: '1',
            ld: '5',
            sv: '5+',
        }],
        keywords: [
            infantry,
            endlessMultitude,
            core,
            hiveTentril,
            tyranids,
        ],
        weapons: [
            weapons.termigantFleshborer,
            weapons.termigantDevourer,
            weapons.termigantSpineFist,
        ],
        abilities:[
            abilities.swarmingMasses,
        ],
        wargear: [
            adrenalGlands,
            toxinSacs,
        ],
    },
    {
        name: 'Hormagaunt',
        type: 'infantry',
        role: 'troops',
        stats: [{
            m: '10"',
            ws: '4+',
            bs: '4+',
            s: '3',
            t: '3',
            w: '1',
            a: '3',
            ld: '5',
            sv: '5+',
        }],
        keywords: [
            infantry,
            endlessMultitude,
            core,
            hiveTentril,
            tyranids,
        ],
        weapons: [
            weapons.hormagauntClaws
        ],
        abilities:[
            abilities.swarmingMasses,
            abilities.boundingLeap
        ],
        wargear: [
            adrenalGlands,
            toxinSacs,
        ],
    },
    {
        name: 'Gargoyle',
        type: 'infantry',
        role: 'troops',
        stats: [{
            m: '12"',
            ws: '4+',
            bs: '4+',
            s: '3',
            t: '3',
            w: '1',
            a: '1',
            ld: '5',
            sv: '6+',
        }],
        keywords: [
            infantry,
            fly,
            endlessMultitude,
            core,
            hiveTentril,
            tyranids,
        ],
        weapons: [
            weapons.termigantFleshborer
        ],
        abilities:[
            abilities.swarmingMasses,
        ],
        wargear: [
            adrenalGlands,
            toxinSacs,
        ],
    },
    {
        name: 'Warriors',
        type: 'infantry',
        role: 'troops',
        stats: [{
            m: '6"',
            ws: '3+',
            bs: '3+',
            s: '5',
            t: '5',
            w: '3',
            a: '3',
            ld: '9',
            sv: '4+',
        }],
        keywords: [
            synapse,
            infantry,
            core,
            hiveTentril,
            tyranids,
        ],
        weapons:[
            weapons.warriorDeathspitter,
            weapons.warriorDevourer,
            weapons.warriorSpinefists,
            weapons.warriorBarbedStrangler,
            weapons.warriorVenomCannon,
            weapons.warriorBonesword,
            weapons.warriorDualBonesword,
            weapons.warriorRendingClaw,
            weapons.warriorScythingtalon,
        ],
        abilities: [
            abilities.warriorSpawning,
            abilities.shadowInTheWarp,
            abilities.goadedToSlaughter,
        ],
        wargear: [
            adrenalGlands,
            toxinSacs,
            fleshHooks,
            {...lashWhip, active: true},
        ],
    },
    {
        name: 'Trygon',
        type: 'monster',
        role: 'fastAttack',
        stats: [{
            m: '10"',
            ws: '3+',
            bs: '3+',
            s: '7',
            t: '7',
            w: '14',
            a: '12',
            ld: '7',
            sv: '3+',
        },{
            m: '8"',
            ws: '4+',
            bs: '4+',
            s: '7',
            t: '7',
            w: '<7',
            a: '12',
            ld: '7',
            sv: '3+',
        },{
            m: '6"',
            ws: '5+',
            bs: '5+',
            s: '7',
            t: '7',
            w: '<4',
            a: '12',
            ld: '7',
            sv: '3+',
        }],
        keywords: [
            monster,
            burrower,
            hiveTentril,
            tyranids,
        ],
        weapons: [
            weapons.trygonBioPulse,
            weapons.trygonTalons,
        ],
        abilities:[
            abilities.deathFromBelow,
            abilities.serpentineCoils,
            abilities.deathThroes
        ],
        wargear: [
            adrenalGlands,
            toxinSacs,
            prehensilePincerTail,
            biostaticRattle,
            {active: true, ...toxinSpike},
        ],
    },
    {
        name: 'Mawloc',
        type: 'monster',
        role: 'fastAttack',
        stats: [{
            m: '10"',
            ws: '3+',
            bs: '3+',
            s: '7',
            t: '7',
            w: '14',
            a: '16',
            ld: '7',
            sv: '3+',
        },{
            m: '8"',
            ws: '4+',
            bs: '4+',
            s: '7',
            t: '7',
            w: '<7',
            a: '16',
            ld: '7',
            sv: '3+',
        },{
            m: '6"',
            ws: '5+',
            bs: '5+',
            s: '7',
            t: '7',
            w: '<4',
            a: '16',
            ld: '7',
            sv: '3+',
        }],
        keywords: [
            monster,
            burrower,
            hiveTentril,
            tyranids,
        ],
        weapons: [
            weapons.mawlocTalons,
        ],
        abilities:[
            abilities.terrorFromTheDeep,
            abilities.distensibleJaws,
            abilities.deathFromBelow,
            abilities.serpentineCoils,
            abilities.deathThroes
        ],
        wargear: [
            adrenalGlands,
            toxinSacs,
            prehensilePincerTail,
            biostaticRattle,
            {active: true, ...toxinSpike},
        ],
    },
    {
        name: 'Raveners',
        type: 'infantry',
        role: 'fastAttack',
        stats: [{
            m: '6"',
            ws: '3+',
            bs: '3+',
            s: '5',
            t: '5',
            w: '3',
            a: '3',
            ld: '9',
            sv: '4+',
        }],
        keywords: [
            infantry,
            core,
            hiveTentril,
            tyranids,
        ],
        weapons:[
            weapons.warriorDeathspitter,
            weapons.warriorDevourer,
            weapons.warriorSpinefists,
            weapons.warriorRendingClaw,
            weapons.warriorScythingtalon,

        ],
        abilities: [
            abilities.deathFromBelow,
            abilities.serpentineBodies,
            abilities.viciousDevouerers,
        ],
        wargear: [
        ],
    },
    {
        name: 'Ripper Swarm',
        type: 'infantry',
        role: 'fastAttack',
        stats: [{
            m: '6"',
            ws: '5+',
            bs: '5+',
            s: '3',
            t: '3',
            w: '4',
            a: '4',
            ld: '4',
            sv: '6+',
        }],
        keywords: [
            swarm,
            hiveTentril,
            tyranids,
        ],
        weapons: [
            weapons.ripperClaws,
            weapons.ripperSpineMaw,
        ],
        abilities: [
            abilities.lesserOrganism,
            abilities.deathFromBelow,
            abilities.burrowAndSqurim,
        ]
    },
    {
        name: 'Parasite of Mortrex',
        type: 'infantry',
        role: 'fastAttack',
        stats: [{
            m: '16"',
            ws: '2+',
            bs: '3+',
            s: '5',
            t: '5',
            w: '6',
            a: '6',
            ld: '8',
            sv: '4+',
        }],
        keywords: [
            character,
            fly,
            synapse,
            hiveTentril,
            tyranids,
        ],
        weapons: [
            weapons.clawedLimbs,
            weapons.barbedOvipositor,
        ],
        abilities: [
            abilities.shadowInTheWarp,
            abilities.parasyticInfection,
            abilities.itItches,
            abilities.shadowHunter,
            abilities.deathFromAbove,
        ]
    },
    {
        name: 'Harpy',
        type: 'monster',
        role: 'flyers',
        stats: [{
            m: '15-40"',
            ws: '3+',
            bs: '3+',
            s: '6',
            t: '7',
            w: '13',
            a: '4',
            ld: '8',
            sv: '3+',
        },
        {
            m: '15-30"',
            ws: '4+',
            bs: '4+',
            s: '6',
            t: '7',
            w: '<7',
            a: '4',
            ld: '8',
            sv: '3+',
        },
        {
            m: '15-20"',
            ws: '5+',
            bs: '5+',
            s: '6',
            t: '7',
            w: '<4',
            a: '4',
            ld: '8',
            sv: '3+',
        }],
        keywords: [
            aircraft,
            monster,
            fly,
            hiveTentril,
            tyranids,
        ],
        weapons: [
            weapons.tyrantVenomCannon,
            weapons.tyrantStranglethron,
            weapons.stingerSalvoes,
            weapons.scythingWings,
        ],
        abilities: [
            abilities.sporeMineCysts,
            abilities.airbornePredator,
            abilities.manoeuvrable,
            abilities.hardToHit,
            abilities.hover,
            abilities.deathThroes,
        ]
    },
    {
        name: 'Hive Crone',
        type: 'monster',
        role: 'flyers',
        stats: [{
            m: '15-40"',
            ws: '3+',
            bs: '3+',
            s: '6',
            t: '7',
            w: '13',
            a: '4',
            ld: '8',
            sv: '3+',
        },
        {
            m: '15-30"',
            ws: '4+',
            bs: '4+',
            s: '6',
            t: '7',
            w: '<7',
            a: '4',
            ld: '8',
            sv: '3+',
        },
        {
            m: '15-20"',
            ws: '5+',
            bs: '5+',
            s: '6',
            t: '7',
            w: '<4',
            a: '4',
            ld: '8',
            sv: '3+',
        }],
        keywords: [
            aircraft,
            monster,
            fly,
            hiveTentril,
            tyranids,
        ],
        weapons: [
            weapons.droolCannon,
            weapons.tentaclids,
            weapons.stingerSalvoes,
            weapons.scythingWings,
            weapons.thoraxSpur,
        ],
        abilities: [
            abilities.huntersInstincts,
            abilities.airbornePredator,
            abilities.manoeuvrable,
            abilities.hardToHit,
            abilities.hover,
            abilities.deathThroes,
        ]
    },
    {
        name: 'Carnifex',
        type: 'monster',
        role: 'heavySupport',
        stats: [{
            m: '8"',
            ws: '3+',
            bs: '4+',
            s: '6',
            t: '7',
            w: '9',
            a: '4',
            ld: '6',
            sv: '2+',
        }],
        keywords: [
            monster,
            core,
            carnifexKeyword,
            hiveTentril,
            tyranids,
        ],
        weapons: [
            weapons.carnifexBioPlasma,
            weapons.carnifexDeathspitter,
            weapons.carnifexDevourer,
            weapons.carnifexSpineBanks,
            weapons.carnifexStranglethornCannon,
            weapons.carnifexVenomCannon,
            weapons.carnifexBoneMace,
            weapons.carnifexCrushingClaw,
            weapons.carnifexScythingTalon,
            weapons.carnifexThresherScythe
        ],
        abilities: [
            abilities.ArmouredExoskeleton,
            abilities.blisteringAssault,
            abilities.monsterousBrood,
            abilities.deathThroes
        ],
        wargear: [
            adrenalGlands,
            toxinSacs,
            acidMawWargear,
            chitinThrons,
            enhancedSenses,
            sporeCysts,
            tusks,
        ],
    },
    {
        name: 'Thornback',
        type: 'monster',
        role: 'heavySupport',
        stats: [{
            m: '6"',
            ws: '3+',
            bs: '4+',
            s: '6',
            t: '7',
            w: '9',
            a: '4',
            ld: '6',
            sv: '2+',
        }],
        keywords: [
            monster,
            core,
            carnifexKeyword,
            hiveTentril,
            tyranids,
        ],
        weapons: [
            weapons.carnifexDeathspitter,
            weapons.carnifexDevourer,
            weapons.carnifexSpineBanks,
            weapons.carnifexStranglethornCannon,
            weapons.carnifexScythingTalon,
            weapons.carnifexThresherScythe
        ],
        abilities: [
            chitinThrons, // this model gets the wargear ability built-in
            abilities.viciousHunter,
            abilities.ArmouredExoskeleton,
            abilities.blisteringAssault,
            abilities.monsterousBrood,
            abilities.deathThroes,
        ],
        wargear: [
            adrenalGlands,
            toxinSacs,
            enhancedSenses,
        ],
    },
    {
        name: 'Screamer Killer',
        type: 'monster',
        role: 'heavySupport',
        stats: [{
            m: '10"',
            ws: '3+',
            bs: '4+',
            s: '6',
            t: '7',
            w: '9',
            a: '10',
            ld: '6',
            sv: '2+',
        }],
        keywords: [
            monster,
            core,
            carnifexKeyword,
            hiveTentril,
            tyranids,
        ],
        weapons: [
            weapons.bioPlasmicScream,
            weapons.screamerKillerTalons,
        ],
        abilities: [
            abilities.ArmouredExoskeleton,
            abilities.blisteringAssault,
            abilities.monsterousBrood,
            abilities.deathThroes,
            abilities.terrifying,
        ],
        wargear: [
            adrenalGlands,
            toxinSacs,
            sporeCysts,
        ],
    },
    {
        name: 'Hive Guard',
        type: 'infantry',
        role: 'heavySupport',
        stats: [{
            m: '6"',
            ws: '4+',
            bs: '3+',
            s: '5',
            t: '6',
            w: '4',
            a: '3',
            ld: '5',
            sv: '3+',
        }],
        keywords: [
            infantry,
            hiveTentril,
            tyranids,
        ],
        weapons: [
            weapons.shockCannon,
            weapons.impalerCannon,
        ],
        abilities:[
            abilities.defensiveStance,
            abilities.synapticGuidence,
        ],
        wargear: [
            adrenalGlands,
            toxinSacs,
        ],
    },
    {
        name: 'Biovore',
        type: 'infantry',
        role: 'heavySupport',
        stats: [{
            m: '5"',
            ws: '4+',
            bs: '4+',
            s: '5',
            t: '5',
            w: '4',
            a: '2',
            ld: '5',
            sv: '4+',
        }],
        keywords: [
            infantry,
            hiveTentril,
            tyranids,
        ],
        weapons: [
            weapons.sporeMineLauncher,
            weapons.chitinBarbedFists,
        ],
        abilities:[
            abilities.seedSporeMines,
        ],
        wargear: [
        ],
    },
    {
        name: 'Exocrine',
        type: 'monster',
        role: 'heavySupport',
        stats: [{
            m: '8"',
            ws: '3+',
            bs: '3+',
            s: '7',
            t: '8',
            w: '15',
            a: '3',
            ld: '7',
            sv: '2+',
        },{
            m: '7"',
            ws: '4+',
            bs: '4+',
            s: '7',
            t: '8',
            w: '<8',
            a: '3',
            ld: '7',
            sv: '2+',
        },{
            m: '5"',
            ws: '5+',
            bs: '5+',
            s: '7',
            t: '8',
            w: '<5',
            a: '3',
            ld: '7',
            sv: '2+',
        }],
        keywords: [
            monster,
            hiveTentril,
            tyranids,
        ],
        weapons: [
            weapons.bioPlasmicCannon,
            weapons.powerfulLimbs,
        ],
        abilities:[
            abilities.symbioticTargeting,
            abilities.deathThroes
        ],
        wargear: [
        ],
    },
    {
        name: 'Tyrannofex',
        type: 'monster',
        role: 'heavySupport',
        stats: [{
            m: '9"',
            ws: '3+',
            bs: '3+',
            s: '7',
            t: '8',
            w: '17',
            a: '4',
            ld: '7',
            sv: '2+',
        },{
            m: '8"',
            ws: '4+',
            bs: '4+',
            s: '7',
            t: '8',
            w: '<9',
            a: '4',
            ld: '7',
            sv: '2+',
        },{
            m: '6"',
            ws: '5+',
            bs: '5+',
            s: '7',
            t: '8',
            w: '<5',
            a: '4',
            ld: '7',
            sv: '2+',
        }],
        keywords: [
            monster,
            hornedChitin,
            hiveTentril,
            tyranids,
        ],
        weapons: [
            weapons.tyrannofexAcidSpray,
            weapons.fleshborerHive,
            weapons.ruptureCannon,
            weapons.stingerSalvoes,
            weapons.powerfulLimbs,
        ],
        abilities:[
            abilities.deathThroes
        ],
        wargear: [
            adrenalGlands,
            toxinSacs
        ],
    },
];