import * as abilities from "./abilities";
import { burrower, character, core, endlessMultitude, feederTendrils, fly, hiveTentril, hiveTyrantKeyword, hornedChitin, infantry, monster, psycher1Keyword, psycher2Keyword, sporeCaster, swarm, synapse, toxicLashes, tyranids } from "./Keywords";
import { acidMawWargear, adrenalGlands, biostaticRattle, chitinThrons, enhancedSenses, extendedCarapace, fleshHooks, infestationNode, lashWhip, prehensilePincerTail, sporeCysts, toxinSacs, tusks } from "./Wargear";
import * as weapons from "./weapons";


export const units = [
    {
        name: 'Hive Tyrant',
        type: 'monster',
        role: 'hq',
        stats: [{
            m: '9"',
            ws: '2+',
            bs: '2+',
            s: '7',
            t: '8',
            w: '12',
            a: '5',
            ld: '10',
            sv: '2+',
        },{
            m: '8"',
            ws: '3+',
            bs: '3+',
            s: '7',
            t: '8',
            w: '<7',
            a: '5',
            ld: '10',
            sv: '2+',
        },{
            m: '6"',
            ws: '4+',
            bs: '4+',
            s: '7',
            t: '8',
            w: '<4',
            a: '5',
            ld: '10',
            sv: '2+',
        }],
        keywords: [
            monster,
            character,
            synapse,
            psycher2Keyword,
            hornedChitin,
            hiveTyrantKeyword,
            hiveTentril,
            tyranids,
        ],
        weapons: [
            weapons.tyrantVenomCannon,
            weapons.tyrantStranglethron,
            weapons.tyrantBonesword,
            weapons.tyrantScythingTalons
        ],
        abilities: [
            abilities.psychicBarrier,
            abilities.willOfTheHiveMind,
            abilities.deathThroes,
            abilities.shadowInTheWarp,
            abilities.relentlessFurocity,
        ],
        wargear: [
            adrenalGlands,
            toxinSacs,
            lashWhip,
        ],
    },
    {
        name: 'Tervigon',
        type: 'monster',
        role: 'hq',
        stats: [{
            m: '8"',
            ws: '3+',
            bs: '3+',
            s: '7',
            t: '8',
            w: '17',
            a: '4',
            ld: '10',
            sv: '2+',
        },{
            m: '7"',
            ws: '4+',
            bs: '4+',
            s: '7',
            t: '8',
            w: '<9',
            a: '4',
            ld: '10',
            sv: '2+',
        },{
            m: '6"',
            ws: '5+',
            bs: '5+',
            s: '7',
            t: '8',
            w: '<5',
            a: '5',
            ld: '10',
            sv: '2+',
        }],
        keywords: [
            monster,
            character,
            synapse,
            psycher1Keyword,
            hiveTentril,
            tyranids,
        ],
        weapons: [
            weapons.tervigonStingerSalvoes,
            weapons.tervigonCrushingClaws,
            weapons.tervigonTalonsStrike,
            weapons.tervigonTalonsSweep,
        ],
        abilities: [
            abilities.spawnTermagants,
            abilities.broodProgenitor,
            abilities.wallOfflesh,
            abilities.deathThroes,
            abilities.shadowInTheWarp,
            abilities.surgingVitality,
        ],
        wargear: [
            adrenalGlands,
            toxinSacs,
        ],
    },
    {
        name: 'Genestealers',
        type: 'infantry',
        role: 'elite',
        stats: [{
            m: '8"',
            ws: '3+',
            bs: '6+',
            s: '4',
            t: '4',
            w: '1',
            a: '4',
            ld: '8',
            sv: '5+',
        }],
        keywords: [
            infantry,
            core,
            feederTendrils,
            hiveTentril,
            tyranids,
        ],
        weapons: [
            weapons.genestealerClaws
        ],
        abilities: [
            abilities.lightningReflexes,
            abilities.vanguardPredator,
            abilities.infiltrationSpawning,
            abilities.insidiousInfestation,
            abilities.insidiousinfestationAction,
        ],
        wargear: [
            toxinSacs,
            fleshHooks,
            infestationNode,
            acidMawWargear,
            extendedCarapace
        ],
    },
    {
        name: 'Venomthrope',
        type: 'infantry',
        role: 'elite',
        stats: [{
            m: '8"',
            ws: '3+',
            bs: '3+',
            s: '5',
            t: '5',
            w: '4',
            a: '5',
            ld: '5',
            sv: '4+',
        }],
        keywords: [
            infantry,
            core,
            fly,
            sporeCaster,
            toxicLashes,
            feederTendrils,
            hiveTentril,
            tyranids,
        ],
        weapons: [
            weapons.venomthropeLashes,
        ],
        abilities: [
            abilities.graspingTendrils,
            abilities.toxicMiasma,
            abilities.foulSpores
        ]
    },
    {
        name: 'Termigant',
        type: 'infantry',
        role: 'troops',
        stats: [{
            m: '6"',
            ws: '4+',
            bs: '4+',
            s: '3',
            t: '3',
            w: '1',
            a: '1',
            ld: '5',
            sv: '5+',
        }],
        keywords: [
            infantry,
            endlessMultitude,
            core,
            hiveTentril,
            tyranids,
        ],
        weapons: [
            weapons.termigantFleshborer,
            weapons.termigantDevourer,
            weapons.termigantSpineFist,
        ],
        abilities:[
            abilities.swarmingMasses,
        ],
        wargear: [
            adrenalGlands,
            toxinSacs,
        ],
    },
    {
        name: 'Hormagaunt',
        type: 'infantry',
        role: 'troops',
        stats: [{
            m: '10"',
            ws: '4+',
            bs: '4+',
            s: '3',
            t: '3',
            w: '1',
            a: '3',
            ld: '5',
            sv: '5+',
        }],
        keywords: [
            infantry,
            endlessMultitude,
            core,
            hiveTentril,
            tyranids,
        ],
        weapons: [
            weapons.hormagauntClaws
        ],
        abilities:[
            abilities.swarmingMasses,
            abilities.boundingLeap
        ],
        wargear: [
            adrenalGlands,
            toxinSacs,
        ],
    },
    {
        name: 'Gargoyle',
        type: 'infantry',
        role: 'troops',
        stats: [{
            m: '12"',
            ws: '4+',
            bs: '4+',
            s: '3',
            t: '3',
            w: '1',
            a: '1',
            ld: '5',
            sv: '6+',
        }],
        keywords: [
            infantry,
            fly,
            endlessMultitude,
            core,
            hiveTentril,
            tyranids,
        ],
        weapons: [
            weapons.termigantFleshborer
        ],
        abilities:[
            abilities.swarmingMasses,
        ],
        wargear: [
            adrenalGlands,
            toxinSacs,
        ],
    },
    {
        name: 'Warriors',
        type: 'infantry',
        role: 'troops',
        stats: [{
            m: '6"',
            ws: '3+',
            bs: '3+',
            s: '5',
            t: '5',
            w: '3',
            a: '3',
            ld: '9',
            sv: '4+',
        }],
        keywords: [
            synapse,
            infantry,
            core,
            hiveTentril,
            tyranids,
        ],
        weapons:[
            weapons.warriorDeathspitter,
            weapons.warriorDevourer,
            weapons.warriorSpinefists,
            weapons.warriorBarbedStrangler,
            weapons.warriorVenomCannon,
            weapons.warriorBonesword,
            weapons.warriorDualBonesword,
            weapons.warriorRendingClaw,
            weapons.warriorScythingtalon,
        ],
        abilities: [
            abilities.warriorSpawning,
            abilities.shadowInTheWarp,
            abilities.goadedToSlaughter,
        ],
        wargear: [
            adrenalGlands,
            toxinSacs,
            fleshHooks,
            lashWhip,
        ],
    },
    {
        name: 'Trygon',
        type: 'monster',
        role: 'fastAttack',
        stats: [{
            m: '10"',
            ws: '3+',
            bs: '3+',
            s: '7',
            t: '7',
            w: '14',
            a: '12',
            ld: '7',
            sv: '3+',
        },{
            m: '8"',
            ws: '4+',
            bs: '4+',
            s: '7',
            t: '7',
            w: '<7',
            a: '12',
            ld: '7',
            sv: '3+',
        },{
            m: '6"',
            ws: '5+',
            bs: '5+',
            s: '7',
            t: '7',
            w: '<4',
            a: '12',
            ld: '7',
            sv: '3+',
        }],
        keywords: [
            monster,
            burrower,
            hiveTentril,
            tyranids,
        ],
        weapons: [
            weapons.trygonBioPulse,
            weapons.trygonTalons,
            weapons.trygonToxinSpike,
        ],
        abilities:[
            abilities.deathFromBelow,
            abilities.serpentineCoils,
            abilities.deathThroes
        ],
        wargear: [
            adrenalGlands,
            toxinSacs,
            prehensilePincerTail,
            biostaticRattle,
        ],
    },
    {
        name: 'Ripper Swarm',
        type: 'infantry',
        role: 'fastAttack',
        stats: [{
            m: '6"',
            ws: '5+',
            bs: '5+',
            s: '3',
            t: '3',
            w: '4',
            a: '4',
            ld: '4',
            sv: '6+',
        }],
        keywords: [
            swarm,
            hiveTentril,
            tyranids,
        ],
        weapons: [
            weapons.ripperClaws,
            weapons.ripperSpineMaw,
        ],
        abilities: [
            abilities.lesserOrganism,
            abilities.deathFromBelow,
            abilities.burrowAndSqurim,
        ]
    },
    {
        name: 'Carnifex',
        type: 'monster',
        role: 'heavySupport',
        stats: [{
            m: '8"',
            ws: '3+',
            bs: '4+',
            s: '6',
            t: '7',
            w: '9',
            a: '4',
            ld: '6',
            sv: '2+',
        }],
        keywords: [
            monster,
            core,
            hiveTentril,
            tyranids,
        ],
        weapons: [
            weapons.carnifexBioPlasma,
            weapons.carnifexDeathspitter,
            weapons.carnifexDevourer,
            weapons.carnifexSpineBanks,
            weapons.carnifexStranglethornCannon,
            weapons.carnifexVenomCannon,
            weapons.carnifexBoneMace,
            weapons.carnifexCrushingClaw,
            weapons.carnifexScythingTalon,
            weapons.carnifexThresherScythe
        ],
        abilities: [
            abilities.ArmouredExoskeleton,
            abilities.blisteringAssault,
            abilities.monsterousBrood,
            abilities.deathThroes
        ],
        wargear: [
            adrenalGlands,
            toxinSacs,
            acidMawWargear,
            chitinThrons,
            enhancedSenses,
            sporeCysts,
            tusks,
        ],
    },
];